/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xmltojava;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;
import org.w3c.dom.Element;
import java.io.File;
import java.util.Arrays;
import java.util.List;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    

    @Override
    public void start(Stage primaryStage) {
        List<String> args = getParameters().getRaw();
        if (args.size() == 0) {
            System.out.println("Please supply field arguments");
    

        }

        try {
            File inputFile = new File("C:/Users/hp/Desktop/xmltojava/app/src/main/java/xmltojava/practical2data.xml");
            DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            Document doc = dBuilder.parse(inputFile);
            doc.getDocumentElement().normalize();
            NodeList nList = doc.getElementsByTagName("record");
            for (int temp = 0; temp < nList.getLength(); temp++) {
                Node nNode = nList.item(temp);
                Element eElement = (Element) nNode;
                System.out.println("{ " );
                for (String field : args) {
                    String fieldValue = eElement.getElementsByTagName(field).item(0).getTextContent();
                    System.out.println("'" + field + "' : '" + fieldValue + "'");
                }
                System.out.println("}");
                System.out.println();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
      
    }

}

